# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chloroform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='alternative',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='target',
            field=models.CharField(blank=True, help_text='An email or a list of emails separated by ;', max_length=2000, verbose_name='Recipient of mails sent with this configuration'),
        ),
    ]
