# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chloroform', '0002_auto_20170614_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='configuration',
            name='metadatas',
            field=models.ManyToManyField(through='chloroform.Requirement', to='chloroform.Metadata'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subject',
            field=models.CharField(default='Contact on {{site}}', help_text='Subject of the notification mail', max_length=1000, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('name', 'Name'), ('phone', 'Phone'), ('address', 'Address'), ('email', 'Email'), ('bool', 'Boolean'), ('text', 'Text'), ('message', 'Message'), ('alternative', 'Choice')], max_length=100, verbose_name='Type of metadata, set the validation and the HTML field'),
        ),
    ]
